package table;

public enum StatusType {
    NOTEBOOK, GAMEPAD, MONITOR, ACCESORIOS, ALMACENAMIENTO, MOVIL, MULTIMEDIA,
    COMPONENTES, COMPUTADORA, DISPOSITIVOS, IMPRESORAS, PERIFERICOS, SERVIDORES,
    SUMINISTROS, UNKNOWN
}
